// CONFIRMED (2026-07-17): duplicate CRL extensions reach the convenience accessors, which
// silently first-match, while extensions_map() rejects the same input.
//
// RFC 5280 forbids a repeated extension. x509-parser's parse path
// (extensions/mod.rs:654 parse_opt_tagged_extensions -> many0) appends everything to a Vec
// with NO dedup; the only DuplicateExtensions checks live inside extensions_map(). So two
// consumers of the same malformed CRL disagree. Real, reachable, severity=info (no panic,
// no memory impact).
//
// dupcrl.der is generated by mkcrl.py (a CRL carrying two CRLNumber (2.5.29.20) extensions).
use x509_parser::prelude::*;
use x509_parser::revocation_list::CertificateRevocationList;

fn main() {
    let der = include_bytes!("dupcrl.der");
    let (_rem, crl) = match CertificateRevocationList::from_der(der) {
        Ok(v) => { println!("[parse] CRL with DUPLICATE CRLNumber extensions ACCEPTED by parser"); v }
        Err(e) => { println!("[parse] REJECTED: {e:?} -> dup never reaches the accessor => FP"); return; }
    };
    println!("[exts]  extensions() len = {}", crl.extensions().len());
    match crl.crl_number() {
        Some(n) => println!("[find]  crl_number() = {n}  (silently first-matched)"),
        None    => println!("[find]  crl_number() = None"),
    }
    match crl.tbs_cert_list.extensions_map() {
        Ok(m)  => println!("[map]   extensions_map() = Ok({} entries) -> NO divergence", m.len()),
        Err(e) => println!("[map]   extensions_map() = Err({e:?}) -> DIVERGENCE CONFIRMED"),
    }
}
